backend:
  build: ./backend
  command: npm run start-dev
  ports:
   - "3000:3000"
   - "8123:8123"
  working_dir: /usr/src/app
  volumes:
   - ./backend:/usr/src/app
frontend:
  build: ./frontend
  command: python -m SimpleHTTPServer 80
  ports:
   - "8080:80"
  volumes:
   - ./frontend:/app
