FROM node:12.4.0
MAINTAINER wiktor.obrebski <wiktor.obrebski@10clouds.com>

# Install file system watcher to auto-reload node during development
# RUN mkdir -p /mnt/external.volume && echo '5' > /mnt/external.volume/network.stats
# RUN /usr/local/bin/npm install -g nodemon@1.19.1
